---
title: "cfbd_plays"
author: "Saiem Gilani"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pull first 3 weeks of 2020 season using `cfbd_plays()`

```{r cfbd_plays, eval=FALSE}
if (!requireNamespace('pacman', quietly = TRUE)){
  install.packages('pacman')
}
pacman::p_load(dplyr,tidyr)
# pacman::p_load_gh("saiemgilani/cfbfastR")
week_vector <- 1:3
year_vector <- 2020
version <- "1.1.0"
weekly_year_df <- expand.grid(year = year_vector, week = week_vector)
### scrape yearly
year_split <- split(weekly_year_df, weekly_year_df$year)
for (i in 1:length(year_split)) {
  i <- 1
  print(paste0("Working on ", year_split[[i]][1, 1]))
  future::plan("multisession")
  progressr::with_progress({
    year_split[[i]] <- year_split[[i]] %>%
      dplyr::mutate(
        pbp = purrr::map2(
          .x = year,
          .y = week,
          cfbd_plays,
          season_type = "both"
        )
      )
    
    Sys.sleep(1)
  })
}

year_split <- lapply(year_split, function(x) {
  x %>%
  dplyr::select(-.data$year, -.data$week) %>% 
    tidyr::unnest(pbp, names_repair = "minimal")
})
all_years <- dplyr::bind_rows(year_split)


```