#' **Data in the package for reference**
#' @name data
NULL
#' **College Football Mapping for Play Types**
#' @rdname data
#' @keywords data
#' @format A data frame with 45 rows and 3 variables:
#'
#' * `id`: Referencing play id
#' * `text`: play type description
#' * `abbreviation`: play type abbreviation used for function call
#'
"cfbd_play_type_df"


#' **College Football Conferences**
#' @rdname data
#' @keywords data
#' @format A data frame with 11 rows and 4 variables:
#'
#' * `id`: Referencing conference id
#' * `name`: Conference name
#' * `short_name`: Short name for Conference
#' * `abbreviation`: Conference abbreviation
#'
"cfbd_conf_types_df"


#' **Minimum Season Accepted by Year-Taking Functions**
#' @rdname data
#' @keywords data
#' @details Generated by `data-raw/min_year_map_df.R`, which walks every
#' exported function taking a `year` argument and probes backwards for the
#' earliest season returning rows. Values are surfaced in each function's
#' `@param year` documentation, so they are only as current as the last
#' `devtools::document()` run following an update of this table.
#' @format A data frame with 85 rows and 4 variables:
#'
#' * `function_name`: Exported cfbfastR function taking a `year` argument
#' * `min_year`: Earliest season the endpoint returns data for
#' * `last_updated`: Date the minimum was last verified against the API
#' * `inherit_min_from`: Function this minimum was inherited from, or `NA` if probed directly
#'
"min_year_map_df"
